---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primevideo
  labels:
    app: primevideo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: primevideo
  template:
    metadata:
      labels:
        app: primevideo
    spec:
      containers:
      - name: primevideo-container
        image: 637423300080.dkr.ecr.eu-west-2.amazonaws.com/prime-video:latest
        ports:
        - containerPort: 3000
...
