---
apiVersion: v1
kind: Service
metadata:
  name: primevideo
  labels:
    app: primevideo
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: primevideo
  type: LoadBalancer
...
